"""Added the lat/lng fields to the Cities table

Revision ID: b45931cd3c0a
Revises: 44175b6b8452
Create Date: 2022-03-09 10:31:58.375538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45931cd3c0a'
down_revision = '44175b6b8452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city_lat', sa.Float(), nullable=True))
    op.add_column('cities', sa.Column('city_lng', sa.Float(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('cities', 'city_lng')
    op.drop_column('cities', 'city_lat')
    # ### end Alembic commands ###
